### PR TITLE
fix: Increase metadata timeout, matching the logic in google-cloud-env

### LINKED ISSUE #226: Fails to detect the GCE environment because of network timeout
Gem version: googleauth-0.8.1

When running on GKE, sometimes the auth library fails to detect that's running inside GCE and exits with 'Could not load the default credentials.'

This happens once in a while, but can be easily reproduced:

Create a short script to just fetch credentials, name it 'try.rb'
```
require "google/cloud/logging"
puts Google::Cloud::Logging.new(project_id: 'foo')
```

run it until it throws an exception:
```
# while ( ruby try.rb ); do echo 'try again...'; done
#<Google::Cloud::Logging::Project:0x0000000217a668>
try again...
#<Google::Cloud::Logging::Project:0x00000001b15840>
try again...
[...]
#<Google::Cloud::Logging::Project:0x00000001819cb8>
try again...
/var/lib/gems/2.3.0/gems/googleauth-0.8.1/lib/googleauth/application_default.rb:76:in `get_application_default': Could not load the default credentials. Browse to (RuntimeError)
https://developers.google.com/accounts/docs/application-default-credentials
for more information
	from /var/lib/gems/2.3.0/gems/googleauth-0.8.1/lib/googleauth/credentials.rb:138:in `from_application_default'
	from /var/lib/gems/2.3.0/gems/googleauth-0.8.1/lib/googleauth/credentials.rb:98:in `default'
	from /var/lib/gems/2.3.0/gems/google-cloud-logging-1.5.0/lib/google/cloud/logging.rb:477:in `default_credentials'
	from /var/lib/gems/2.3.0/gems/google-cloud-logging-1.5.0/lib/google/cloud/logging.rb:405:in `new'
	from try.rb:4:in `<main>'
```

The exception thrown is  `#<Faraday::TimeoutError wrapped=#<Net::ReadTimeout: Net::ReadTimeout>>` which seems to come from [this line](https://github.com/googleapis/google-auth-library-ruby/blob/master/lib/googleauth/compute_engine.rb#L74): `req.options.timeout = 0.1`

See the comment a few lines up:
```
            # Note: the explicit `timeout` below is a workaround. The underlying
            # issue is that resolving an unknown host on some networks will take
            # 20-30 seconds; making this timeout short fixes the issue, but
            # could lead to false negatives in the event that we are on GCE, but
            # the metadata resolution was particularly slow. The latter case is
            # "unlikely".
```

Maybe we could come up with a better way to detect that we're on GCE or create an environment variable to force it?

### PR DESCRIPTION
**Pull request by dazuma**
Keep `open_timeout` low to keep the "fail-fast" behavior on non-gce hosts. But increase overall `timeout` to reduce false negatives since some metadata service instances can take a few moments to warm up. (In particular, this warmup behavior is sometimes observed on Titanium-based hosting.) This matches the settings we converged on in the google-cloud-env gem.

Fixes #226

### CODE REVIEW

**Comment by blowmage** [comment]
Rebase?

File: lib/googleauth/compute_engine.rb [hunk 1]
```diff
@@ -59,20 +59,15 @@ class << self
         extend Memoist
 
         # Detect if this appear to be a GCE instance, by checking if metadata
-        # is available
+        # is available.
+        #
+        # TODO: This should use google-cloud-env.
```
Comment (blowmage) [inline lib/googleauth/compute_engine.rb]: Do you want to move this comment inside the method body? So it isn't used as documentation?

Comment (dazuma) [reply lib/googleauth/compute_engine.rb]: Yeah good call. Moved.

**Comment by dazuma** [comment]
Rebased.
